export { getSupabaseClient, isSupabaseReady } from '@/services/supabase/client'
export { authService } from '@/services/auth.service'
export { profilesService } from '@/services/profiles.service'
export { storageService, CLOTHING_BUCKET, AVATAR_BUCKET } from '@/services/storage.service'
export { productsService } from '@/services/products.service'
export { likesService } from '@/services/likes.service'
export { savedService } from '@/services/saved.service'
export { messagesService } from '@/services/messages.service'
export { notificationsService } from '@/services/notifications.service'
export { mercadopagoService } from '@/services/mercadopago.service'
export { ordersService } from '@/services/orders.service'
